/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_car_rental;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_car_rental.classes.Booking;
import java_car_rental.classes.Customer;
import java_car_rental.classes.Car;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.TimeZone;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class Form_BookingList extends javax.swing.JFrame {

    /**
     * Creates new form Form_BookingList
     */
    
    Booking bok = new Booking();
    ArrayList<Booking> bok_list = bok.BookingList();
    int id = 0;
    String add_edit;
    
    public Form_BookingList(String add_or_edit) 
    {
        add_edit = add_or_edit ;
        
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null) ;
        
        populateJtableWithBooking();
        
        //Set jtable row height
        jTable_Booking.setRowHeight(30);
        
        if(add_edit.equals("add"))
        {
            jButton_select_booking.setEnabled(false);
        }
        
        displayImage(jLabel_list_logo.getWidth(),jLabel_list_logo.getHeight(),getClass().getResource("images/list.png").getFile(),jLabel_list_logo);
        
    }
    
    public void displayImage (int width, int height, String image_path, JLabel label){
        //get the image
        ImageIcon imageIco = new ImageIcon(image_path);
        //resize the image
        Image image = imageIco.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        //set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }
    
    
    //populte jTable with brand 
    public void populateJtableWithBooking()
    {
        //clear array list 
        bok_list.clear();
        //populate arraylist
        bok_list = bok.BookingList();   
        //jtable columns
        String[] columnsName = {"ID","Car Id","Customer ID","PickUp City","PickUp Address","PickUp Date","PickUp Time","DropOff City","DropOff Address",
            "DropOff Date","DropOff Time","Total Price"};
        
        //jtable rows 
        Object[][] rows = new Object[bok_list.size()][columnsName.length];
        
        for(int i=0;i<bok_list.size();i++)
        {
            rows[i][0]  =bok_list.get(i).getId();
            rows[i][1]  =bok_list.get(i).getCar_id(); 
            rows[i][2]  =bok_list.get(i).getCustomer_id();
            rows[i][3]  =bok_list.get(i).getPickup_city();
            rows[i][4]  =bok_list.get(i).getPickup_address();
            rows[i][5]  =bok_list.get(i).getPickup_date();
            rows[i][6]  =bok_list.get(i).getPickup_time();
            rows[i][7]  =bok_list.get(i).getDropoff_city();
            rows[i][8]  =bok_list.get(i).getDropoff_address();
            rows[i][9]  =bok_list.get(i).getDropoff_date();
            rows[i][10]  =bok_list.get(i).getDropoff_time();
            rows[i][11]  =bok_list.get(i).getTotal_price();
            
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        jTable_Booking.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_list_logo = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Booking = new javax.swing.JTable();
        jButton_select_booking = new javax.swing.JButton();
        jButton_print_booking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("All Booked Cars");

        jLabel_close.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel_list_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_list_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable_Booking.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTable_Booking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Booking.setSelectionBackground(new java.awt.Color(0, 204, 153));
        jTable_Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Booking);

        jButton_select_booking.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_select_booking.setText("Select Booking");
        jButton_select_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_select_bookingActionPerformed(evt);
            }
        });

        jButton_print_booking.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_print_booking.setText("Print");
        jButton_print_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_print_bookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton_select_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_print_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_select_booking)
                    .addComponent(jButton_print_booking))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // close the form when clicked
        this.dispose();

        
        
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jTable_BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BookingMouseClicked

        // get the selected rand

        //        index = jTable_Customers.getSelectedRow();
        //        int id =Integer.parseInt(jTable_Customers.getValueAt(index, 0).toString());
        //        String fullname = jTable_Customers.getValueAt(index, 1).toString();
        //        //String birthdate = jTable_Customers.getValueAt(index, 2).toString();
        //        String phone = jTable_Customers.getValueAt(index, 3).toString();
        //        String email = jTable_Customers.getValueAt(index, 4).toString();
        //        String address = jTable_Customers.getValueAt(index, 5).toString();
    }//GEN-LAST:event_jTable_BookingMouseClicked

    private void jButton_select_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_select_bookingActionPerformed

        try{
            // get the selected Booking :
            int index =jTable_Booking.getSelectedRow();
            String id =jTable_Booking.getValueAt(index, 0).toString();
            String car_id = jTable_Booking.getValueAt(index, 1).toString();
            String customer_id = jTable_Booking.getValueAt(index, 2).toString();
            String pickup_city = jTable_Booking.getValueAt(index, 3).toString();
            String pickup_address = jTable_Booking.getValueAt(index, 4).toString();
            String pickup_date = jTable_Booking.getValueAt(index, 5).toString();
            String pickup_time = jTable_Booking.getValueAt(index, 6).toString();
            String dropoff_city = jTable_Booking.getValueAt(index, 7).toString();
            String dropoff_address = jTable_Booking.getValueAt(index, 8).toString();
            String dropoff_date = jTable_Booking.getValueAt(index, 9).toString();
            String dropoff_time = jTable_Booking.getValueAt(index, 10).toString();
            String total_price = jTable_Booking.getValueAt(index, 11).toString();

            //set the customer id & name in the book a car form
            Form_Booking_Edit_Remove.displayBooking(id, car_id , customer_id ,pickup_city, pickup_address , pickup_date , pickup_time , dropoff_city , dropoff_address ,
                    dropoff_date , dropoff_time , total_price);

            //close this form
            this.dispose();
        }catch(Exception ex)
        {
            Logger.getLogger(Form_BookingList.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null , "The Program Get a Problem With Selecting \n Error ->  " + ex.getMessage(),"Not Selected ",1);
        }
    }//GEN-LAST:event_jButton_select_bookingActionPerformed

    private void jButton_print_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_print_bookingActionPerformed
        
        try {
            // print the sleected booking
            File file = new File("/Users/mac/booking.txt");
            
            if(!file.exists())
            {
                file.createNewFile();
                
            }
            
            FileWriter fw = new FileWriter (file.getAbsolutePath());
            BufferedWriter bw = new BufferedWriter(fw);
            
            int index =jTable_Booking.getSelectedRow();
            String id =jTable_Booking.getValueAt(index, 0).toString();
            String car_id = jTable_Booking.getValueAt(index, 1).toString();
            String customer_id = jTable_Booking.getValueAt(index, 2).toString();
            String pickup_city = jTable_Booking.getValueAt(index, 3).toString();
            String pickup_address = jTable_Booking.getValueAt(index, 4).toString();
            String pickup_date = jTable_Booking.getValueAt(index, 5).toString();
            String pickup_time = jTable_Booking.getValueAt(index, 6).toString();
            String dropoff_city = jTable_Booking.getValueAt(index, 7).toString();
            String dropoff_address = jTable_Booking.getValueAt(index, 8).toString();
            String dropoff_date = jTable_Booking.getValueAt(index, 9).toString();
            String dropoff_time = jTable_Booking.getValueAt(index, 10).toString();
            String total_price = jTable_Booking.getValueAt(index, 11).toString();
            String customer_fullname = new Customer().getCustomerById(Integer.valueOf(customer_id)).getFullname();
            String car_Model = new Car().getCarById(Integer.valueOf(customer_id)).getModel();
            
            
            
            Date dateNow = new Date();
            // Afficher la date et la localisation
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            dateFormat.setTimeZone(TimeZone.getDefault());
            String dateStr = dateFormat.format(dateNow);
            
            
            
            
            
            bw.write("Badeel");
            bw.write("\n");
            bw.write("\n");
            bw.write("Date et heure de la facture : "+dateStr);
            bw.write("\n");
            bw.write("\n");
            bw.write("\n");
            bw.write("\n");
            bw.write("Booking ID : "+id);
            bw.write("\n---------------------------------\n");
            bw.write("Customer ID : "+customer_id+"  Customer FullName : "+customer_fullname);
            bw.write("\n---------------------------------\n");
            bw.write("Car ID : "+car_id+"  Car Model : "+car_Model);
            bw.write("\n---------------------------------\n");
            bw.write("Pick UP City  : "+pickup_city);
            bw.write("\n---------------------------------\n");
            bw.write("Pick UP Address: "+pickup_address);
            bw.write("\n---------------------------------\n");
            bw.write("Pick UP Date: "+pickup_date);
            bw.write("\n---------------------------------\n");
            bw.write("Pick UP Time: "+pickup_time);
            bw.write("\n---------------------------------\n");
            bw.write("Drop Off City: "+dropoff_city);
            bw.write("\n---------------------------------\n");
            bw.write("Drop Off Address: "+dropoff_address);
            bw.write("\n---------------------------------\n");
            bw.write("Drop Off Date: "+dropoff_date);
            bw.write("\n---------------------------------\n");
            bw.write("Drop Off Time: "+dropoff_time);
            bw.write("\n---------------------------------\n");
            bw.write("Total Price : "+total_price);
            
            
            bw.close();
            fw.close();
            
             JOptionPane.showMessageDialog(null , "Data Has Been Exported","Exported ",1);
            
        } catch (IOException ex) {
            Logger.getLogger(Form_BookingList.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null , "The Program Get a Problem With Exportation \n Error ->  " + ex.getMessage(),"Not Exported ",1);
        }
       
        
    }//GEN-LAST:event_jButton_print_bookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_BookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_BookingList("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_print_booking;
    private javax.swing.JButton jButton_select_booking;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_list_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Booking;
    // End of variables declaration//GEN-END:variables
}
