/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_car_rental;

import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import java_car_rental.classes.Car;
import java_car_rental.classes.brand_Cls;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author mac
 */
public class Form_Cars extends javax.swing.JFrame {

    /**
     * Creates new form Form_Cars
     */
    
    Car car  = new Car();
    brand_Cls brand = new brand_Cls();
    HashMap<Integer, String> map= brand.brandsHashMap();
        
    public Form_Cars() {
        
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null) ;
        
        //add radiobutton to button group
        ButtonGroup btn_group = new ButtonGroup ();
        btn_group.add(jRadioButton_Gear_Automatic);
        btn_group.add(jRadioButton_Gear_Manuel);
        
        //populate comboBox with brands
        populateComboboxBrands();
        
        displayImage(jLabel_brands_logo.getWidth(),jLabel_brands_logo.getHeight(),getClass().getResource("images/automobile.png").getFile(),jLabel_brands_logo);
        
    }
    
    public void displayImage (int width, int height, String image_path, JLabel label){
        //get the image
        ImageIcon imageIco = new ImageIcon(image_path);
        //resize the image
        Image image = imageIco.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        //set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }
    
    //create a function to populate the jcombobox with brands   
    //and to do that we will use a ***hashmap*** 
    public void  populateComboboxBrands()
    {
                
        for(String s : map.values())
        {
            jComboBox_brand.addItem(s);
        }
    }
    
    
    //create a function to check empty fields
    public boolean verify()
    {

        String model = jTextField_model.getText();
        String _class = jTextField_class.getText();

        
        
        if (!model.trim().equals("") && !_class.trim().equals(""))
        {
            return true;
            
        }else{
            JOptionPane.showMessageDialog(null , "Enter Valid Model and Class ","Invalid Info",2);
            return false;
        
        }   
            
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        int max1 =20 ;
        int min1=2;
        int step1=1;
        int i1 = 2;
        SpinnerModel spinner_model1 = new SpinnerNumberModel(i1, min1, max1, step1);
        jSpinner_passengers1 = new javax.swing.JSpinner(spinner_model1);
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_brands_logo = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_Add_Car = new javax.swing.JButton();
        jButton_Add_Images = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox_Features_AirCond = new javax.swing.JCheckBox();
        jCheckBox_Features_Sunroof = new javax.swing.JCheckBox();
        jCheckBox_Features_Airbags = new javax.swing.JCheckBox();
        jCheckBox_Features_HeatedSeats = new javax.swing.JCheckBox();
        jCheckBox_Features_NavigationSystems = new javax.swing.JCheckBox();
        jCheckBox_Features_GPS = new javax.swing.JCheckBox();
        jCheckBox_Features_Bluetooth = new javax.swing.JCheckBox();
        jCheckBox_Features_ElectricWindows = new javax.swing.JCheckBox();
        jComboBox_brand = new javax.swing.JComboBox<>();
        jComboBox_fuel = new javax.swing.JComboBox<>();
        jComboBox_color = new javax.swing.JComboBox<>();
        jTextField_class = new javax.swing.JTextField();
        jSpinner_passengers = new javax.swing.JSpinner();
        jTextField_model = new javax.swing.JTextField();
        jButton_Brand_List = new javax.swing.JButton();
        jRadioButton_Gear_Automatic = new javax.swing.JRadioButton();
        jRadioButton_Gear_Manuel = new javax.swing.JRadioButton();
        jButton_Reset = new javax.swing.JButton();
        jLabel_brand_id = new javax.swing.JLabel();
        int max =100000 ;
        int min=10;
        int step=1;
        int i = 10;
        SpinnerModel spinner_model = new SpinnerNumberModel(i, min, max, step);
        jSpinner_Price = new javax.swing.JSpinner(spinner_model);
        jButton_Cars_List = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_id = new javax.swing.JSpinner();
        jButton_SearchById = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel12.setText("Passengers:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(155, 89, 182));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cars");

        jLabel_close.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel_brands_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_brands_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("    Brand:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Model:");

        jButton_Add_Car.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Add_Car.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Add_Car.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Car.setText("Add");
        jButton_Add_Car.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_CarActionPerformed(evt);
            }
        });

        jButton_Add_Images.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Add_Images.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Add_Images.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Images.setText("Add Images");
        jButton_Add_Images.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Images.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ImagesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("Fuel:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Color:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setText("Passengers:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("     GearBox:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setText("     Class:");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel10.setText("Price/day:");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Features:");

        jCheckBox_Features_AirCond.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_AirCond.setText("Air Conditioning");

        jCheckBox_Features_Sunroof.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_Sunroof.setText("Sunroof");

        jCheckBox_Features_Airbags.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_Airbags.setText("Airbags");

        jCheckBox_Features_HeatedSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_HeatedSeats.setText("Heated Seats");

        jCheckBox_Features_NavigationSystems.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_NavigationSystems.setText("Navigation systems");

        jCheckBox_Features_GPS.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_GPS.setText("GPS");

        jCheckBox_Features_Bluetooth.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_Bluetooth.setText("Bluetooth");

        jCheckBox_Features_ElectricWindows.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCheckBox_Features_ElectricWindows.setText("Electric Windows");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_AirCond)
                    .addComponent(jCheckBox_Features_Airbags))
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_HeatedSeats)
                    .addComponent(jCheckBox_Features_Sunroof))
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_NavigationSystems)
                    .addComponent(jCheckBox_Features_Bluetooth))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_ElectricWindows)
                    .addComponent(jCheckBox_Features_GPS))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Features_AirCond)
                    .addComponent(jCheckBox_Features_Sunroof)
                    .addComponent(jCheckBox_Features_Bluetooth)
                    .addComponent(jCheckBox_Features_ElectricWindows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Features_Airbags)
                    .addComponent(jCheckBox_Features_HeatedSeats)
                    .addComponent(jCheckBox_Features_NavigationSystems)
                    .addComponent(jCheckBox_Features_GPS))
                .addGap(32, 32, 32))
        );

        jComboBox_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_brandActionPerformed(evt);
            }
        });

        jComboBox_fuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gas", "Diesel" }));

        jComboBox_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Black ", "Red", "Yellow", "Green", "Blue", "Grey", "Brown", "Orange" }));

        jButton_Brand_List.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Brand_List.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Brand_List.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Brand_List.setText("Brands List");
        jButton_Brand_List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Brand_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Brand_ListActionPerformed(evt);
            }
        });

        jRadioButton_Gear_Automatic.setText("Automatic");
        jRadioButton_Gear_Automatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Gear_AutomaticActionPerformed(evt);
            }
        });

        jRadioButton_Gear_Manuel.setText("Manuel");

        jButton_Reset.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Reset.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Reset.setText("Reset");
        jButton_Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jLabel_brand_id.setText("#");

        jButton_Cars_List.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Cars_List.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Cars_List.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cars_List.setText("Cars List");
        jButton_Cars_List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cars_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cars_ListActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel13.setText("              Id:");

        jButton_SearchById.setText("Search");
        jButton_SearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchByIdActionPerformed(evt);
            }
        });

        jButton_Remove.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Remove.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove.setText("Remove");
        jButton_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jButton_Edit.setBackground(new java.awt.Color(142, 68, 173));
        jButton_Edit.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton_Edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit.setText("Edit");
        jButton_Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner_id, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_fuel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_model)
                            .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_brand_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton_SearchById)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel10))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_class)
                    .addComponent(jSpinner_passengers)
                    .addComponent(jRadioButton_Gear_Automatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Gear_Manuel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Add_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Brand_List, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Cars_List, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Add_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_class, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner_passengers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton_Gear_Automatic)
                                .addComponent(jRadioButton_Gear_Manuel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_SearchById, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_brand_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_model, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_fuel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_color, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Brand_List, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cars_List, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // close the form when clicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_Add_CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_CarActionPerformed
        //add a new car     
        int brand = Integer.parseInt(jLabel_brand_id.getText());
        String model = jTextField_model.getText();
        String fuel = jComboBox_fuel.getSelectedItem().toString();
        String color = jComboBox_color.getSelectedItem().toString();
        String _class_ = jTextField_class.getText();
        int passengers = (int)jSpinner_passengers.getValue();
        String gearbox = "automatic";
        int price = Integer.parseInt(jSpinner_Price.getValue().toString());
        //car features
        String air_cond = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seates = "no";
        String nav_sys = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if(jRadioButton_Gear_Manuel.isSelected()){ gearbox = "manuel";}
        if(jCheckBox_Features_AirCond.isSelected()){ air_cond = "yes";}
        if(jCheckBox_Features_Airbags.isSelected()){ airbags = "yes";}
        if(jCheckBox_Features_Sunroof.isSelected()){ sunroof = "yes";}
        if(jCheckBox_Features_HeatedSeats.isSelected()){ heated_seates = "yes";}
        if(jCheckBox_Features_Bluetooth.isSelected()){ nav_sys = "yes";}
        if(jCheckBox_Features_NavigationSystems.isSelected()){ bluetooth = "yes";}
        if(jCheckBox_Features_ElectricWindows.isSelected()){ elec_win = "yes";}
        if(jCheckBox_Features_GPS.isSelected()){ gps = "yes";}
        
        if(verify())
        {
        car.addCar(brand,model,fuel,color,_class_,passengers,gearbox,price,
                air_cond,airbags,sunroof,heated_seates,nav_sys,bluetooth,elec_win,gps);
        }
        
    }//GEN-LAST:event_jButton_Add_CarActionPerformed

    private void jButton_Add_ImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ImagesActionPerformed
         // open the Form_CarsImages
         Form_CarsImages frm_carImg = new Form_CarsImages();
         frm_carImg.setVisible(true);
        
    }//GEN-LAST:event_jButton_Add_ImagesActionPerformed

    private void jButton_Brand_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Brand_ListActionPerformed
       // open the Form_BrandsList
         Form_BrandsList frm_brdList = new Form_BrandsList();
         frm_brdList.setVisible(true);
    }//GEN-LAST:event_jButton_Brand_ListActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // Button  to Reset  all Fields to there  default value
        jComboBox_brand.setSelectedIndex(0);
        jTextField_model.setText("");
        jLabel_brand_id.setText("#");
        jComboBox_fuel.setSelectedIndex(0);
        jComboBox_color.setSelectedIndex(0);
        jTextField_class.setText("");
        jSpinner_passengers.setValue(0);
        jSpinner_Price.setValue(0);
        jRadioButton_Gear_Automatic.setSelected(true);
         
        //car features
        jCheckBox_Features_AirCond.setSelected(false);  
        jCheckBox_Features_Airbags.setSelected(false);  
        jCheckBox_Features_Bluetooth.setSelected(false);  
        jCheckBox_Features_ElectricWindows.setSelected(false);  
        jCheckBox_Features_GPS.setSelected(false);  
        jCheckBox_Features_HeatedSeats.setSelected(false);  
        jCheckBox_Features_NavigationSystems.setSelected(false);  
        jCheckBox_Features_Sunroof.setSelected(false);  
        
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jComboBox_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_brandActionPerformed
        // Get the Selected brand id 
        int brand_id=0;
        for(Map.Entry<Integer, String> entry : map.entrySet())
        {
            if(entry.getValue().equals(jComboBox_brand.getSelectedItem().toString()))
            {
                brand_id = entry.getKey();
            }
        
        }
        jLabel_brand_id.setText(String.valueOf(brand_id));
    }//GEN-LAST:event_jComboBox_brandActionPerformed

    private void jButton_Cars_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cars_ListActionPerformed
        // Display car List Form
         Form_CarsList frm_carList = new Form_CarsList();
         frm_carList.setVisible(true);
        
    }//GEN-LAST:event_jButton_Cars_ListActionPerformed

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        // remove car 
        int id = (int)jSpinner_id.getValue();   
        int confirm = JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Delete This Car","confirm",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION)
        {
            car.removeCar(id);
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // edit car
        int id = (int)jSpinner_id.getValue();    
        int brand = Integer.parseInt(jLabel_brand_id.getText());
        String model = jTextField_model.getText();
        String fuel = jComboBox_fuel.getSelectedItem().toString();
        String color = jComboBox_color.getSelectedItem().toString();
        String _class_ = jTextField_class.getText();
        int passengers = (int)jSpinner_passengers.getValue();
        String gearbox = "automatic";
        int price = Integer.parseInt(jSpinner_Price.getValue().toString());
        //car features
        String air_cond = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seates = "no";
        String nav_sys = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if(jRadioButton_Gear_Manuel.isSelected()){ gearbox = "manuel";}
        if(jCheckBox_Features_AirCond.isSelected()){ air_cond = "yes";}
        if(jCheckBox_Features_Airbags.isSelected()){ airbags = "yes";}
        if(jCheckBox_Features_Sunroof.isSelected()){ sunroof = "yes";}
        if(jCheckBox_Features_HeatedSeats.isSelected()){ heated_seates = "yes";}
        if(jCheckBox_Features_Bluetooth.isSelected()){ nav_sys = "yes";}
        if(jCheckBox_Features_NavigationSystems.isSelected()){ bluetooth = "yes";}
        if(jCheckBox_Features_ElectricWindows.isSelected()){ elec_win = "yes";}
        if(jCheckBox_Features_GPS.isSelected()){ gps = "yes";}
        
        if(verify())
        {
        car.editCar(brand,model,fuel,color,_class_,passengers,gearbox,price,
                air_cond,airbags,sunroof,heated_seates,nav_sys,bluetooth,elec_win,gps,id);
        }
        
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_SearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchByIdActionPerformed
            // Search car By id:
        
        int car_id = (int) jSpinner_id.getValue();
        Car new_car = car.getCarById(car_id);
        
        //reset all fields
        jButton_ResetActionPerformed(null);
        
        if(new_car == null)
        {
             JOptionPane.showMessageDialog(null , "No Car With This Id ","Invalid Info",2);
        }
        if(new_car!=null)
        {
            jSpinner_id.setValue(car_id);
            jComboBox_brand.setSelectedItem(map.get(new_car.getBrand()));
            jTextField_model.setText(new_car.getModel());
            jLabel_brand_id.setText(String.valueOf(new_car.getBrand()));
            jComboBox_fuel.setSelectedItem(new_car.getFuel());
            jComboBox_color.setSelectedItem(new_car.getColor());
            jTextField_class.setText(new_car.getClass_());
            jSpinner_passengers.setValue(new_car.getPassengers());
            jSpinner_Price.setValue(new_car.getPrice());
            if(new_car.getGearbox().equals("manual")){
            jRadioButton_Gear_Automatic.setSelected(true);
            }else{
            jRadioButton_Gear_Manuel.setSelected(true);   
            }
            //car features
            
            if(new_car.getAir_cond().equals("yes")){jCheckBox_Features_AirCond.setSelected(true);  }
            if(new_car.getAirbag().equals("yes")){jCheckBox_Features_Airbags.setSelected(true);  }
            if(new_car.getBluetooth().equals("yes")){jCheckBox_Features_Bluetooth.setSelected(true);  }
            if(new_car.getElec_window().equals("yes")){jCheckBox_Features_ElectricWindows.setSelected(true);  }
            if(new_car.getGps().equals("yes")){jCheckBox_Features_GPS.setSelected(true);  }
            if(new_car.getHeated_seats().equals("yes")){jCheckBox_Features_HeatedSeats.setSelected(true);  }
            if(new_car.getNav_sys().equals("yes")){jCheckBox_Features_NavigationSystems.setSelected(true);  }
            if(new_car.getSunroof().equals("yes")){jCheckBox_Features_Sunroof.setSelected(true);  }
        }
    }//GEN-LAST:event_jButton_SearchByIdActionPerformed

    private void jRadioButton_Gear_AutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Gear_AutomaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_Gear_AutomaticActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Cars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Car;
    private javax.swing.JButton jButton_Add_Images;
    private javax.swing.JButton jButton_Brand_List;
    private javax.swing.JButton jButton_Cars_List;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_SearchById;
    private javax.swing.JCheckBox jCheckBox_Features_AirCond;
    private javax.swing.JCheckBox jCheckBox_Features_Airbags;
    private javax.swing.JCheckBox jCheckBox_Features_Bluetooth;
    private javax.swing.JCheckBox jCheckBox_Features_ElectricWindows;
    private javax.swing.JCheckBox jCheckBox_Features_GPS;
    private javax.swing.JCheckBox jCheckBox_Features_HeatedSeats;
    private javax.swing.JCheckBox jCheckBox_Features_NavigationSystems;
    private javax.swing.JCheckBox jCheckBox_Features_Sunroof;
    private javax.swing.JComboBox<String> jComboBox_brand;
    private javax.swing.JComboBox<String> jComboBox_color;
    private javax.swing.JComboBox<String> jComboBox_fuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_brand_id;
    private javax.swing.JLabel jLabel_brands_logo;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_Gear_Automatic;
    private javax.swing.JRadioButton jRadioButton_Gear_Manuel;
    private javax.swing.JSpinner jSpinner_Price;
    private javax.swing.JSpinner jSpinner_id;
    private javax.swing.JSpinner jSpinner_passengers;
    private javax.swing.JSpinner jSpinner_passengers1;
    private javax.swing.JTextField jTextField_class;
    private javax.swing.JTextField jTextField_model;
    // End of variables declaration//GEN-END:variables
}
